name: Setup

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' # FIXME: use .python-version
        cache: 'pip'
        cache-dependency-path: './requirements_for_test.txt'
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: make generate-version-file
      shell: bash
    - run: pip install -r requirements_for_test.txt
      shell: bash
    - run: make babel # FIXME: remove unless we want to translate too
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
