name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          tags: notification-admin:latest
          build-args: ADMIN_COMMIT=${{ github.sha }}
          outputs: type=docker,dest=/tmp/notification-admin.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Cache image
        id: notif-admin-docker
        uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
  lint-flake:
    name: "Python linting: Flake"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make lint-flake
  lint-js-and-css:
    name: "Javascript and CSS linting"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make lint-js-and-css
  order-check:
    name: Check imports order
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make order-check
  js-tests:
    name: Javascript tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make js-tests
  tests:
    name: Python tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make test
