name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: notification-admin:latest
          outputs: type=docker,dest=/tmp/notification-admin.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Cache image
        id: notif-admin-docker
        uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin

  lint-black:
    name: "Python linting: Black"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make lint-black
  lint-flake:
    name: "Python linting: Flake"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make lint-flake
  lint-js:
    name: "Javascript linting: Prettier"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make lint-js
  order-check:
    name: Check imports order
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make order-check
  type-check:
    name: Typecheck with Mypy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make type-check
  js-tests:
    name: Javascript tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make js-tests
  tests:
    name: Python tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make test
  test-translations:
    name: Check for missing translations
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-admin.tar
          key: ${{ github.sha }}-admin
      - run: docker load --input /tmp/notification-admin.tar
      - run: docker run --rm notification-admin:latest make test-translations
